const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Create Company Schema
const CompanySchema = new Schema({
  name: {
    type: String,
    required: true
  }
});

module.exports = Company = mongoose.model("company", CompanySchema);

// Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYmM4MTNmNDg1ZDI0NWNmMjNkYzIxYiIsImVtYWlsIjoibWF4QG1heGFsdGVuYS5jb20iLCJ1c2VybmFtZSI6Im1heGFsdGVuYSIsIm5hbWUiOiJNYXggQWx0ZW5hIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8yYmQ0MzE5NTNkNWZkYmY1YmMyNDVkY2UxMjk0NGE5Yj9zPTIwMCZyPXBnJmQ9bW0iLCJhZG1pbl9yb2xlIjp0cnVlLCJpYXQiOjE1MzkxMTg3NzF9.I2IZRUGxUgilKKU5xdluASDSlhR_nogUjL03WqS5ur0

// Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYmM4NmZiZWE2YjJlNjNhODM0ZDQzYiIsImVtYWlsIjoiam9obmRvZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpvaG5kb2UiLCJuYW1lIjoiSm9obiBEb2UiLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzI5YTFkZjQ2NDZjYjM0MTdjMTk5OTRhNTlhM2UwMjJhP3M9MjAwJnI9cGcmZD1tbSIsImFkbWluX3JvbGUiOmZhbHNlLCJpYXQiOjE1MzkxMjAwMjJ9.DF-ZBn9o48jFizPOo4iGcNP0lG1-snY7GL6woymAW_Q
